### ISSUE TITLE
git-slice-pull-issue workflow won't work when issues are created in a different repo.

### ISSUE THREAD

**Issue by collinewait** [GitStartHQ/git-slice-tools#60]
I observed that some repositories use issues from other repositories for example [https://github.com/mattermost/mattermost-webapp](https://github.com/mattermost/mattermost-webapp) use issues from [https://github.com/mattermost/mattermost-server](https://github.com/mattermost/mattermost-server).
After defining the upstream for the webapp, `git-slice-pull-issue` won't work since issues are created from the server repo.

**Comment by collinewait** [comment]
Does having the option to override the default upstream for `git-slice-pull-issue` resolve this?

**Comment by phunguyenmurcul** [comment]
@collinewait Yeah, it doesn't support it for now, let me update `pull-issue` job with full issue link. I will inform you when it's ready

**Comment by phunguyenmurcul** [comment]
@collinewait I have just released a new version 1.7.2 of `git-slice-tools` workflow, could you please follow this https://github.com/GitStartHQ/git-slice-tools#upgrade-git-slice-tools-workflow to upgrade it on your repo. In this version you can use issue link in pull-issue workflow dispatch. 
Feel free to create a bug issue if there is any issue.
Thank you.
